server:
  port: 8091
  address: 0.0.0.0

spring:
  profiles:
    active:
      - prod

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 676573584701-3c89qt2j86j4rvg66tv9rut58pe47jld.apps.googleusercontent.com
            clientSecret: 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

