server:
  port: 8091
  address: 0.0.0.0

spring:
  profiles:
    active:
      - prod

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  jooq:
    sql-dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <your_client_id_here>.apps.googleusercontent.com
            clientSecret: <your_secret_here>

