version: "3.9"
services:
  server:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 20s
      retries: 3
      start_period: 5s

  application-jar:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-jar
    depends_on:
      - server
    ports:
      - "8091:8091"

  react-app:
    networks:
      - default
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile-react
      args:
        - REACT_APP_SERVICES_HOST=/frontend
    depends_on:
      - server
      - application-jar
    ports:
      - "80:80"

networks:
  default:
    driver: bridge

volumes:
  postgres-db:
